"""Add notification_id column to Complaint table

Revision ID: 0f2365031287
Revises: a8377fa58e47
Create Date: 2024-04-23 20:08:48.094751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2365031287'
down_revision = 'a8377fa58e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'notification', ['notification_id'], ['notification_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notification_id')

    # ### end Alembic commands ###
