"""Updated PAssword_hash column

Revision ID: 3cc103a23dc7
Revises: 87f4c9dcfcf7
Create Date: 2024-04-22 15:37:12.129706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc103a23dc7'
down_revision = '87f4c9dcfcf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###
