"""Resolved user conflict

Revision ID: 87f4c9dcfcf7
Revises: 111b751d2266
Create Date: 2024-04-22 15:24:46.714276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f4c9dcfcf7'
down_revision = '111b751d2266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint('complaint_notification_id_fkey', type_='foreignkey')
        batch_op.drop_column('notification_id')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint('request_notification_id_fkey', type_='foreignkey')
        batch_op.drop_column('notification_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('request_notification_id_fkey', 'notification', ['notification_id'], ['notification_id'])

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('complaint_notification_id_fkey', 'notification', ['notification_id'], ['notification_id'])

    # ### end Alembic commands ###
