"""Updated User table

Revision ID: 8f65c5d0faf8
Revises: afc02d8d1bb4
Create Date: 2024-04-23 12:56:38.699763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f65c5d0faf8'
down_revision = 'afc02d8d1bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_constraint('tenant_email_key', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('tenant_email_key', ['email'])

    # ### end Alembic commands ###
