"""Added all the FK

Revision ID: 913cb1fb999f
Revises: 2eceba9c8205
Create Date: 2024-04-22 14:55:52.953417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913cb1fb999f'
down_revision = '2eceba9c8205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complaint_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'request', ['request_id'], ['id'])
        batch_op.create_foreign_key(None, 'complaint', ['complaint_id'], ['complaint_id'])

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'notification', ['notification_id'], ['notification_id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'notification', ['notification_id'], ['notification_id'])

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'notification', ['notification_id'], ['notification_id'])

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reminder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['users_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'reminder', ['reminder_id'], ['reminder_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reminder_id')
        batch_op.drop_column('users_id')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notification_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notification_id')

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notification_id')

    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('request_id')
        batch_op.drop_column('complaint_id')

    # ### end Alembic commands ###
